### ISSUE TITLE
Implement SPI Flash Memory Driver

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Firmware#21]
# Overview

Faraday has an onboard Flash memory IC that communicates using SPI and can be used to store various data. This is a new addition to REV B. I need to verify the device is working, SPI connected properly, and implement a driver.

**NOTE:** A fully working driver is not needed for initial release. Just the confirmation that a full driver can be implemented with no board changes!

**To-Do**
- [x] Verify proper hardware connections
- [x] Verify read/write data
- [ ] Implement full driver
# References

References to use the Flash memory IC.
- [25LQ080 Datasheet](http://www.issi.com/WW/pdf/25LQ080.pdf)
# Progress
## Verify Hardware

Hardware is connected properly. I updated the GPIO mapping header file to implement the SPI chip select and HOLD pins.

![image](https://cloud.githubusercontent.com/assets/339144/19513359/80fbf9c6-95a4-11e6-8513-cac4c14dae01.png)

![image](https://cloud.githubusercontent.com/assets/339144/19513368/86323c02-95a4-11e6-9349-4ce319c4136a.png)

![image](https://cloud.githubusercontent.com/assets/339144/19513373/8aa3dbf6-95a4-11e6-8477-76fe59e4ebd7.png)
## Read/Write Data

The command table summery is shown below:

![image](https://cloud.githubusercontent.com/assets/339144/19513398/9e3abbb2-95a4-11e6-95d9-ff310b1212a9.png)
- I was able to read device info and status
- IC is touchy on timing
- IC seems to require a toggling of the CE pin prior to a new command
- I wrote data and can read from the memory addresses to verify but it is unreliable. I cannot get an erase to work. to re-write.

**Comment by kb1lqd** [comment]
Closing and shelving until a later time. Testing and development shows little need for this for initial release and onboard flash/local computer can provide adequate support for memory.
